### ISSUE TITLE
Github workstream

### ISSUE THREAD

**Issue by hugelgupf** [opencomputeproject/OSF#3]
If I remember correctly, I signed up for the GitHub workstream in OSF. Would you mind giving me some admin access to the repo? I would like to add notifications from this repo to our LinuxBoot Slack channel.

Also, are you on Slack? All LinuxBoot developers are on https://u-root.slack.com. You can sign up here: http://slack.u-root.com/

**Comment by insomniacslk** [comment]
Shall all the LinuxBoot/u-root core contributors get access?

**Comment by hugelgupf** [comment]
I think that might be a bit much, especially since there are 15 other workstreams. If we're just going to link to LinuxBoot from here (for now), not everybody needs access.

**Comment by hugelgupf** [comment]
ping @rajeevsharma1 ?

**Comment by rajeevsharma1** [comment]
@hugelgupf can you check? I have given you the write permission.
