### ISSUE TITLE
OSF Requirements doc viewable in GitHub

### ISSUE THREAD

**Issue by hugelgupf** [opencomputeproject/OSF#4]
The current doc is a .docx. GitHub can't automatically render this in the browser -- it'd be preferable to have something like that. Either a PDF, or even more preferred, something we can easily change in a commit - markdown?

**Comment by GanShun** [comment]
I would strongly suggest something like markdown

**Comment by rajeevsharma1** [comment]
agreed. I will create the first markdown version today and delete the .docx.
Lets all use this .md going forward.
I'll update here once the md is ready

**Comment by rajeevsharma1** [comment]
requirements md file is now in the following location in github
OSF/OSF_Requirements/OSF_Requirements.md
